In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
df = pd.read_excel (r"C:\Users\Admin\TensorFlow\insurance_data.xlsx")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [17]:
X_train

age  affordibility
6    60              0
0    22              1
3    52              0
1    25              0
5    56              1
11   27              1
9    18              1
18   18              0
16   58              0
8    61              1
13   49              0
2    47              1
12   29              1
15   25              1
4    46              1

In [18]:
len(X_train)

15

In [19]:
df.shape

(19, 3)

In [44]:
X_train_scaled =X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [45]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(
             optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy']
             )
model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50


C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 827ms/step - accuracy: 0.4667 - loss: 0.7318
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4667 - loss: 0.7314
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4667 - loss: 0.7310
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4667 - loss: 0.7306
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4667 - loss: 0.7302
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.4667 - loss: 0.7298
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.4667 - loss: 0.7294
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.4667 - loss: 0.7289
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.4667 - loss: 0.7285
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - accuracy: 0.4667 - loss: 0.7281
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4667 - loss: 0.7277
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4667 - loss: 0.7273
Epoch 13/

In [46]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.5000 - loss: 0.9390


[0.9389593005180359, 0.5]

In [47]:
X_test_scaled

age  affordibility
10  0.28              1
17  0.19              1
7   0.62              0
14  0.55              0

In [48]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[0.7627059 ],
       [0.7468767 ],
       [0.6317625 ],
       [0.61615217]], dtype=float32)

In [49]:
y_test

10    0
17    0
7     1
14    1
Name: bought_insurance, dtype: int64

In [50]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.950538 ],
        [0.9509699]], dtype=float32),
 array([-0.04954824], dtype=float32))

In [55]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [56]:
def predction_function(age, affordibility):
    weighted_sum=coef[0]*age+ coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [57]:
predction_function(.28,1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13752\1668309685.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7627059099862172

In [58]:
predction_function(.19,1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13752\1668309685.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7468767887683624

In [59]:
def log_loss(y_true, y_predicted):
    eplison = 1e-15
    y_predicted_new=[max(i, eplison) for i in y_predicted]
    y_predicted_new=[min(i, 1-eplison) for i in y_predicted_new]
    y_predicted_new= np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [61]:
def sigmoid_numpy(X):
    return 1 /(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [70]:
def gradient_descent(age, affordibility, y_true, epochs):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)

    for i in range(epochs):
        weighted_sum= w1 * age + w2* affordibility +bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true, y_predicted)
        w1d= (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
        w2d= (1/n)*np.dot(np.transpose(affordibility), (y_predicted-y_true))

        bias_d= np.mean(y_predicted-y_true)
        w1 = w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias- rate* bias_d
        print(f'Epochs:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
    return w1, w2 ,bias
    

In [71]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000)

Epochs:0, w1:0.9575180733847628, w2:0.9612148016107159, bias:-0.1268196418718266, loss:0.7318436806936693
Epochs:1, w1:0.9214429922320216, w2:0.9316707447071724, bias:-0.23741683377884293, loss:0.6957141191186739
Epochs:2, w1:0.8912034069764311, w2:0.9106757978174581, bias:-0.3332698749941874, loss:0.6689769764631047
Epochs:3, w1:0.86613265276183, w2:0.8973051690404147, bias:-0.4160938927357905, loss:0.6494461147414256
Epochs:4, w1:0.8455422592952163, w2:0.8905344342007203, bias:-0.48765356487443856, loss:0.6352403502081009
Epochs:5, w1:0.8287737845231066, w2:0.8893418798196375, bias:-0.54963191383284, loss:0.6248588993146449
Epochs:6, w1:0.8152289035047264, w2:0.8927738900172645, bias:-0.6035548587539248, loss:0.617168854417729
Epochs:7, w1:0.804382537563594, w2:0.8999788676145496, bias:-0.6507589578150231, loss:0.6113484951440267
Epochs:8, w1:0.7957847846600024, w2:0.910218973286619, bias:-0.6923874730874685, loss:0.6068185148528289
Epochs:9, w1:0.7890564527395456, w2:0.9228682799426

(5.070212297535425, 2.88608829806048, -3.9640037822219445)

In [72]:
coef, intercept

(array([[0.950538 ],
        [0.9509699]], dtype=float32),
 array([-0.04954824], dtype=float32))