In [16]:
import numpy as np
y_predicted=np.array([1,1,0,0,1])
y_true= np.array([0.30,0.7,1,0,0.5])


In [17]:
def mae(y_true, y_predicted):
    total_error=0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error:", total_error)

    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [18]:
mae(y_true, y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [19]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [21]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [22]:
np.log([0.0000000000000000000001])

array([-50.65687205])

In [28]:
eplison = 1e-15

In [39]:
y_predicted_new=[max(i, eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [40]:
y_predicted_new=[min(i, 1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [41]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [43]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [45]:
def log_loss(y_true, y_predicted):
    eplison = 1e-15
    y_predicted_new=[max(i, eplison) for i in y_predicted]
    y_predicted_new=[min(i, 1-eplison) for i in y_predicted_new]
    y_predicted_new= np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [46]:
log_loss(y_true, y_predicted)

17.2696280766844