In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
df = pd.read_excel (r"C:\Users\Admin\TensorFlow\insurance_data.xlsx")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [9]:
X_train

age  affordibility
6    60              0
0    22              1
3    52              0
1    25              0
5    56              1
11   27              1
9    18              1
18   18              0
16   58              0
8    61              1
13   49              0
2    47              1
12   29              1
15   25              1
4    46              1

In [10]:
len(X_train)

15

In [11]:
df.shape

(19, 3)

In [12]:
X_train_scaled =X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [13]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(
             optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy']
             )
model.fit(X_train_scaled, y_train, epochs=50)

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.4667 - loss: 0.7318
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4667 - loss: 0.7314
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4667 - loss: 0.7310
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4667 - loss: 0.7306
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4667 - loss: 0.7302
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4667 - loss: 0.7298
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4667 - loss: 0.7294
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4667 - loss: 0.7289
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4667 - loss: 0.7285
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.4667 - loss: 0.7281
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4667 - loss: 0.7277
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4667 - loss: 0.7273
Epo

In [14]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.5000 - loss: 0.9390


[0.9389593005180359, 0.5]

In [15]:
X_test_scaled

age  affordibility
10  0.28              1
17  0.19              1
7   0.62              0
14  0.55              0

In [16]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[0.7627059 ],
       [0.7468767 ],
       [0.6317625 ],
       [0.61615217]], dtype=float32)

In [17]:
y_test

10    0
17    0
7     1
14    1
Name: bought_insurance, dtype: int64

In [18]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.950538 ],
        [0.9509699]], dtype=float32),
 array([-0.04954824], dtype=float32))

In [19]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [20]:
def predction_function(age, affordibility):
    weighted_sum=coef[0]*age+ coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [21]:
predction_function(.28,1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10168\1668309685.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7627059099862172

In [22]:
predction_function(.19,1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10168\1668309685.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7468767887683624

In [23]:
def log_loss(y_true, y_predicted):
    eplison = 1e-15
    y_predicted_new=[max(i, eplison) for i in y_predicted]
    y_predicted_new=[min(i, 1-eplison) for i in y_predicted_new]
    y_predicted_new= np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [24]:
def sigmoid_numpy(X):
    return 1 /(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [27]:
class myNN:
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0

    def fit(self, X,y, epochs, loss_thresold):
        self.w1, self.w2, self.bias= self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold)
        
    def gradient_descent(age, affordibility, y_true, epochs, loss_thresold):
        w1=w2=1
        bias=0
        rate=0.5
        n=len(age)

        for i in range(epochs):
            weighted_sum= w1 * age + w2* affordibility +bias
            y_predicted = sigmoid_numpy(weighted_sum)

            loss = log_loss(y_true, y_predicted)
            w1d= (1/n)*np.dot(np.transpose(age), (y_predicted-y_true))
            w2d= (1/n)*np.dot(np.transpose(affordibility), (y_predicted-y_true))

            bias_d= np.mean(y_predicted-y_true)
            w1 = w1-rate*w1d
            w2=w2-rate*w2d
            bias=bias- rate* bias_d
            print(f'Epochs:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            if loss<= loss_thresold:
                break

        return w1, w2, bias

In [31]:
customModel =myNN()
customModel.fit(X_train_scaled, y_train, epochs=5, loss_thresold=0.28)

TypeError: myNN.gradient_descent() takes 5 positional arguments but 6 were given

In [ ]:
customModel.predicted