In [4]:
import numpy as np
import scipy.linalg as linalg

a =np.array([[3,4], [2,5]])
b= np.array([10,9])
print("Solution: ", linalg.solve(a,b))

array =np.array([[1,2,3],[4,5,6], [8,8,9]])

print("Numpy Array")
print(array)
print()

determinant = linalg.det(array)
print("Determinant: ", determinant)
print()

inverse_array = linalg.inv(array)
print("Inverse: ")
print(inverse_array)
print()
print("Matrix - inverse product:")
print(array @ inverse_array)
print()

array2 =np.array([[1,-2,0], [-2,1,0],[0,0,3]])

eg_val, eg_vec = linalg.eig(array2)
print(eg_val)
print(eg_vec)

P= eg_vec
P_inverse=linalg.inv(eg_vec)

D=[]
for index, eg_value in enumerate(eg_val):
    row = np.zeros((3))
    D.append(row)
D=np.array(D)

print(P @ D @ P_inverse)


Solution:  [2. 1.]
Numpy Array
[[1 2 3]
 [4 5 6]
 [8 8 9]]

Determinant:  -3.0

Inverse: 
[[ 1.         -2.          1.        ]
 [-4.          5.         -2.        ]
 [ 2.66666667 -2.66666667  1.        ]]

Matrix - inverse product:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 3.+0.j -1.+0.j  3.+0.j]
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
