In [7]:
#Arithmetic Function
import numpy as np
var = np.array([1,2,3,4,4,5,6,6])

print("Min : ", np.min(var), np.argmin(var))
print("Max : ", np.max(var), np.argmax(var))
print("Sqrt : ", np.sqrt(var))

Min :  1 0
Max :  6 6
Sqrt :  [1.         1.41421356 1.73205081 2.         2.         2.23606798
 2.44948974 2.44948974]


In [6]:
var1 = np.array([[2,3,4],[5,7,7]])

print(np.min(var1, axis=1))

[2 5]


In [8]:
#Var Sin value
varsin = np.array([1,2,34])
print(np.sin(varsin))

[0.84147098 0.90929743 0.52908269]


In [10]:
#Var Cos value
varcos = np.array([1,2,34])
print(np.sin(varcos))
print(np.cumsum(varcos))

[0.84147098 0.90929743 0.52908269]
[ 1  3 37]
