In [1]:
#Arithmetic Oerations

import numpy as np
var = np.array([1,2,3,4,5])
varAdd = var + 3
print(varAdd)


[4 5 6 7 8]


In [3]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])


varAdd = var1 + var2
print(varAdd)

[ 2  4  6  8 10]


In [4]:
#Substraction
var = np.array([1,2,3,4,5])
varSub = var - 3
print(varSub)

[-2 -1  0  1  2]


In [5]:
#Multiplication
var = np.array([1,2,3,4,5])
varMulty = var * 3
print(varMulty)

[ 3  6  9 12 15]


In [6]:
#Divsion
var = np.array([1,2,3,4,5])
varDiv = var / 3
print(varDiv)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [7]:
#modulus
var = np.array([1,2,3,4,5])
varMod = var % 3
print(varMod)

[1 2 0 1 2]


In [8]:
#2D Array

varArray = np.array([[1,2,3,4,5],[1,2,3,4,5]])
varArray2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(varArray)
print()
print(varArray2)
print()

varAdd2 = varArray + varArray2
print(varAdd2)

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
