In [6]:
#Broadcasting
import numpy as np
var = np.array([1,2,3,4])
print(var.shape)
print(var)


var1 = np.array([[1],[2],[3]])
print(var1.shape)
print()
print(var1)
print()
print(var + var1)

(4,)
[1 2 3 4]
(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [9]:
x = np.array([[1], [2]])
print(x.shape)

y = np.array([[1,2,3], [1,3,4]])
print(x + y)

(2, 1)
[[2 3 4]
 [3 5 6]]
