In [1]:
#DATATYPE

import numpy as np

var = np.array([1, 2,3 ,4])

print("Data Type : ", var.dtype)

Data Type :  int32


In [3]:
var = np.array([1.2, 2.3,3.4 ,4.5])

print("Data Type : ", var.dtype)

Data Type :  float64


In [4]:
var = np.array(["A", "B", "C", "D"])

print("Data Type : ", var.dtype)

Data Type :  <U1


In [6]:
#List Of characters that are used t represented dtype in Numpy
# i= integer, b= bolean, u= unsnged integers, f= float, c= complex float, m= timedelta, M=datatime, O= object, S= string, U=unicode string, v=the fixed of memory fr other types (void)

x = np.array([1, 2,3, 4], dtype =np.int8)
print("Data Type : ", x.dtype)
print(x)

Data Type :  int8
[1 2 3 4]


In [8]:
#convert from int to float
x1 = np.array([1, 2,3, 4], dtype = "f")
print("Data Type : ", x1.dtype)
print(x1)


Data Type :  float32
[1. 2. 3. 4.]


In [11]:
x2 = np.array([1, 2,3, 4])

new = np.float32(x2)

new1= np.int_(new)

print("Data Type : ", x2.dtype)
print(x2)
print(new)
print("Data Type : ", new.dtype)
print(new1)
print("Data Type : ", new1.dtype)

Data Type :  int32
[1 2 3 4]
[1. 2. 3. 4.]
Data Type :  float32
[1 2 3 4]
Data Type :  int32


In [12]:
x3 = np.array([1, 2,3, 4])

new_1 = x3.astype(float)

print(x3)
print(new_1)


[1 2 3 4]
[1. 2. 3. 4.]
