In [10]:
import numpy as np
var = np.array([1,2,3,4])
print(var)
print(type(var))
x = np.append(var, 6)
v= np.insert(var, 2, 40)
print(v)
print(x)

[1 2 3 4]
<class 'numpy.ndarray'>
[ 1  2 40  3  4]
[1 2 3 4 6]


In [8]:
#2D Matrix
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print(type(var1))

v1 = np.insert(var1, 2, [22,23], axis =1)
print(v1)

[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[ 1  2 22  3  4]
 [ 1  2 23  3  4]]


In [11]:
#Delete Funtion
var_del = np.array([1,2,3,4])
print(var_del)
print(type(var_del))
x = np.delete(var, 2)

print(x)


[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 4]
