In [2]:
#Iterating
import numpy as np
x = np.array([9,8,7,6,5,4,3])

print(x)
print()
for i in x:
    print(i)


[9 8 7 6 5 4 3]

9
8
7
6
5
4
3


In [5]:
x1 = np.array([[9,8,7,6,5,4,3], [9,8,7,6,5,4,3]])

print(x1)
print()
for j in x1:
    print(j)
print()

for k in x1:
    for l in k:
        print(l)


[[9 8 7 6 5 4 3]
 [9 8 7 6 5 4 3]]

[9 8 7 6 5 4 3]
[9 8 7 6 5 4 3]

9
8
7
6
5
4
3
9
8
7
6
5
4
3


In [21]:
# 3d array
x3 = np.array([[[9,8,7,6], [19,18,17,16]]])

print(x3)
print(x3.ndim)
print()

for y in x3:
    for z in y:
        for p in z:
        
            print(p)


[[[ 9  8  7  6]
  [19 18 17 16]]]
3

9
8
7
6
19
18
17
16


In [23]:
# 3d array
x3 = np.array([[[9,8,7,6], [19,18,17,16]]])

print(x3)
print(x3.ndim)
print()

for a in np.nditer(x3):
   print(a)

[[[ 9  8  7  6]
  [19 18 17 16]]]
3

9
8
7
6
19
18
17
16


In [24]:
# 3d array
x3 = np.array([[[9,8,7,6], [19,18,17,16]]])

print(x3)
print(x3.ndim)
print()

for a,d in np.ndenumerate(x3):
   print(a, d)

[[[ 9  8  7  6]
  [19 18 17 16]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 19
(0, 1, 1) 18
(0, 1, 2) 17
(0, 1, 3) 16
