In [1]:
# 1D Array Join
import numpy as np

x = np.array([1,2,3])
y = np.array([3,4,5])

arr = np.concatenate((x, y))

print(arr)

[1 2 3 3 4 5]


In [4]:
#2D Array

x2 = np.array([[1,2,3],[1,2,3]])
y2 = np.array([[3,4,5],[3,4,5]])

arr2 = np.concatenate((x2, y2), axis=1)

print(x2)
print()
print(y2)
print()
print(arr2)

[[1 2 3]
 [1 2 3]]

[[3 4 5]
 [3 4 5]]

[[1 2 3 3 4 5]
 [1 2 3 3 4 5]]


In [9]:
x3 = np.array([1,2,3])
y3 = np.array([3,4,5])

arr3 = np.stack((x3, y3), axis=1)
arr4 = np.hstack((x3, y3)) # row
arr5 = np.vstack((x3, y3)) # column
arr6 = np.dstack((x3, y3)) # height

print(arr3)
print()
print(arr4)
print()
print(arr5)
print()
print(arr6)

[[1 3]
 [2 4]
 [3 5]]

[1 2 3 3 4 5]

[[1 2 3]
 [3 4 5]]

[[[1 3]
  [2 4]
  [3 5]]]


In [12]:
#========================================SPLIT Array==============================================
var = np.array([1,2,3,4,5,6])
print(var)

array = np.array_split(var,3)
print()
print(array)

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
