In [21]:
#Matrix
import numpy as np
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
var3 = np.matrix([[1,3],[1,2]])
print(var)
print(type(var))
print()

print("Addition: ",var+var2)
print()
print("Substraction : \n",var-var2)
print("Multiplication: \n", var.dot(var2))

#Transpose
print("TRanspose Function: \n", var.T)

#Swapaxes
print("Swapaxes: \n", np.swapaxes(var, 0,1))

#Inverse Method

print("Inverse: \n",np.linalg.inv(var3))

#Power Function

print("Power: \n",np.linalg.matrix_power(var3, 2))

#DeterMine Matrix
print("Determinate Matrix: \n",np.linalg.det(var3))



[[1 2]
 [1 2]]
<class 'numpy.matrix'>

Addition:  [[2 4]
 [2 4]]

Substraction : 
 [[0 0]
 [0 0]]
Multiplication: 
 [[3 6]
 [3 6]]
TRanspose Function: 
 [[1 1]
 [2 2]]
Swapaxes: 
 [[1 1]
 [2 2]]
Inverse: 
 [[-2.  3.]
 [ 1. -1.]]
Power: 
 [[4 9]
 [3 7]]
Determinate Matrix: 
 -1.0
