In [5]:
#Array
import numpy as np
x=[1, 2,3,4]
y= np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [4]:
l=[]
for i in range(1,5):
    int_1 = int(input ("enter :"))
    l.append(int_1)

print(np.array(l))

enter : 2
enter : 3
enter : 4
enter : 4


['2' '3' '4' '4']


In [8]:
#2-D array
ar2 = np.array([[1, 2, 3, 4, 5], [2,4,6,8,9]])
print(ar2)
print(ar2.ndim)      

[[1 2 3 4 5]
 [2 4 6 8 9]]
2


In [10]:
#3-D array
ar3 = np.array([[[1, 2, 3, 4, 5], [2,4,6,8,9], [2,4,6,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]
  [2 4 6 8 9]
  [2 4 6 8 9]]]
3


In [14]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
