In [1]:
## RANDOM

# 1.Rand() -for one dimention
import numpy as np
var = np.random.rand(4)
print(var)

[0.19109332 0.35743785 0.00822141 0.33807786]


In [2]:
#Fr 2 dimentional
var1 = np.random.rand(2,5)
print(var1)


[[0.51898776 0.63180038 0.60201137 0.52669393 0.28725802]
 [0.03932035 0.05970241 0.8663153  0.98646103 0.40212311]]


In [3]:
#random 2. randn()-close to zero
var2 = np.random.randn(5)
print(var2)

[-1.75351853  1.27908134 -0.30085155 -0.14029703 -0.44742861]


In [4]:
#RANDOM 3.ranf()

var3= np.random.ranf(4)
print(var3)

[0.02194896 0.03246776 0.73493181 0.11338165]


In [5]:
#RANDOM 4.randint()-  given a range

var_randint = np.random.randint(0,10,8)
print(var_randint)

[1 4 3 8 6 4 8 7]
