In [3]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6,7,8])

x = np.where((var%2) == 0)
print(x)

(array([1, 3, 5], dtype=int64),)


In [11]:
var2 = np.array([1, 2, 3, 4, 5, 6,7,8])

x2 = np.searchsorted(var2,[9, 10,11], side= "right")
print(x2)

[8 8 8]


In [13]:
#Sorted Array
var_sort = np.array([1, 2, 3, 7,8,4, 9,5, 6,7,8])

x3 = np.sort(var_sort)
print(x3)

[1 2 3 4 5 6 7 7 8 8 9]


In [15]:
var_sort2 = np.array([[1, 2, 3, 7,8,4, 9,5], [5,5,6,43,6,7,7,9]])

x4 = np.sort(var_sort2)
print(x4)

[[ 1  2  3  4  5  7  8  9]
 [ 5  5  6  6  7  7  9 43]]


In [17]:
#Filter Function
var_filt = np.array(["s", "d", "b", "u"])
f = [True, False, False, True]

new_a = var_filt[f]
print(new_a)

['s' 'u']
