In [1]:
#Shape
import numpy as np

var = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [4]:
var_1 = np.array([1,2,3,4], ndmin =4)
print(var_1)
print(var_1.ndim)
print()
print(var_1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [8]:
#REshape
var_2 = np.array([1,2,3,4,5,6])
print(var_2)
print(var_2.ndim)
print()
x = var_2.reshape(3, 2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [10]:
var_3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var_3)
print(var_3.ndim)
print()
x1 = var_3.reshape(2,3, 2)
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [11]:
var_3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var_3)
print(var_3.ndim)
print()
x1 = var_3.reshape(2,3, 2)
print(x1)
print(x1.ndim)

print()

one= x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
