In [6]:
#Shuffle Funtion
import numpy as np
var_shu = np.array([1,2,3,4,5])

np.random.shuffle(var_shu)
print(var_shu)

[3 4 2 1 5]


In [10]:
#Unique Function
var_uni = np.array([1,2,3,6,5,3,4,5])

x = np.unique(var_uni, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 6, 4, 3], dtype=int64), array([1, 1, 2, 1, 2, 1], dtype=int64))


In [12]:
var2= np.array([1,2,3,4,5,6])
y= np.resize(var2, (2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [20]:
#Faltten Function
var2= np.array([1,2,3,4,5,6])
y= np.resize(var2, (2,3))
print("Flatten Function : ",y.flatten(order="F"))
print("Ravel Function : ",y.ravel(order="A"))

Flatten Function :  [1 4 2 5 3 6]
Ravel Function :  [1 2 3 4 5 6]
