In [5]:
#Slicing

import numpy as np

var = np.array([1,2,3,4])
print(var)
print()
print("2 to 4 : ", var[1:5])
print("2 to End : ", var[1:])

print("Start to 4 : ", var[:4])

print("Stop : ", var[::2])

[1 2 3 4]

2 to 4 :  [2 3 4]
2 to End :  [2 3 4]
Start to 4 :  [1 2 3 4]
Stop :  [1 3]


In [8]:
var1 = np.array([[11,21,31,41],[1,2,3,4],[11,12,13,14]])
print(var1)
print()

print("2 to 4 : ", var1[1,1:])

[[11 21 31 41]
 [ 1  2  3  4]
 [11 12 13 14]]

2 to 4 :  [2 3 4]
