In [5]:
#ZERO
import numpy as np

arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,4))

print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#ONEs

arr_one = np.ones(4)
arr_one1 = np.ones((3,4))

print(arr_one)
print()
print(arr_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#EMPTY
arr = np.empty(4)
print(arr)

[1. 1. 1. 1.]


In [9]:
#RANGE
arr_ran = np.arange(4)
print(arr_ran)

[0 1 2 3]


In [10]:
#DIAGONAL
arr_dia = np.eye(4)
print(arr_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#LIN-SAPCE ARRAY
arr_lin = np.linspace(1,10, num=5)
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]
